# Generated by Django 5.2.8 on 2025-12-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'In Asteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
